name: Publish dataset zips

on:
  push:
    branches: [ "main" ]
    paths:
      - "datasets/audio/**/*"
      - "datasets/image/**/*"
      - "datasets/text/**/*"
      - ".github/workflows/publish-datasets.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Prep Bird audio
        run: |
          pushd ./datasets/audio/birds
          git clone https://huggingface.co/datasets/greenarcade/wav2vec2-vd-bird-sound-classification-dataset birds
          python prep_birds.py
          mv ./birds/test ./birds/train ./
          rm -rf ./birds
          popd

      - name: Prep Flowers102
        run: |
          pushd ./datasets/image/flowers102
          wget -qO- https://www.robots.ox.ac.uk/~vgg/data/flowers/102/102flowers.tgz | tar xz
          python prep_flowers102.py
          rm -rf ./jpg *json *.ipynb
          popd

      - name: Zip Files
        run: |
          ln -s datasets data
          tar -czf att-faces.tar.gz data/image/att-faces
          tar -czf metfaces.tar.gz data/image/metfaces
          tar -czf clouds.tar.gz data/image/clouds
          tar -czf flowers.tar.gz data/image/flowers
          tar -czf bob-ross.tar.gz data/image/bob-ross
          tar -czf rev-sils.tar.gz data/image/rev-sils
          tar -czf keyword-extraction.tar.gz data/text/keyword-extraction
          tar --exclude='data/audio/instruments/raw' -czf instruments.tar.gz data/audio/instruments
          tar --exclude='data/audio/birds/prep_birds.py' -czf birds.tar.gz data/audio/birds
          tar --exclude='data/image/0801-500/all' -czf 0801-500.tar.gz data/image/0801-500
          tar --exclude='data/image/flowers102/prep_flowers102.py' -czf flowers102.tar.gz data/image/flowers102
          tar --exclude='data/image/forest-tree/raw' -czf forest-tree.tar.gz data/image/forest-tree
          tar --exclude='data/image/lfw/raw' -czf lfw.tar.gz data/image/lfw

      - name: Tag Release
        id: tag
        run: |
          GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-8)
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          TAG_NAME=${{ github.ref_name }}-$(git log --format=%h -1)
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
          tag_name: ${{ steps.tag.outputs.TAG_NAME }}
          token: ${{ secrets.PUSH_TOKEN }}
