name: Publish dataset web

on:
  push:
    branches: [ "main" ]
    paths:
      - "datasets/csv/**/*"
      - "datasets/json/**/*"
      - ".github/workflows/publish-web.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Push gh-pages
        run: |
          COMMIT_MSG=${{ github.ref_name }}-$(git log --format=%h -1)
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan gh-pages
          git reset .
          touch .nojekyll
          git add .nojekyll ./datasets/csv/*.csv ./datasets/json/*.json
          git commit -m $COMMIT_MSG
          git push -f origin gh-pages
